local nvim_lsp = require('lspconfig')
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require('lspkind').init()

-- Diagnostics symbols for display in the sign column.
local signs = { Error = "", Warn = "", Hint = "", Info = "" }
for type, icon in pairs(signs) do
    local hl = "DiagnosticSign" .. type
    vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
end
vim.cmd('setlocal omnifunc=v:lua.vim.lsp.omnifunc')


-- Get rid of ugly text to the right and let Lspsaga deal with it
vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
        underline = true,
        signs = true,
    }
)

-- Python
nvim_lsp.pylsp.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
-- GoLang
nvim_lsp.gopls.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
-- JavaScript and Typescript
nvim_lsp.tsserver.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
-- PHP
nvim_lsp.intelephense.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
    settings = {
        intelephense = {
            stubs = {
                'Core',
                'Ev',
                'FFI',
                'LuaSandbox',
                'PDO',
                'Parle',
                'Phar',
                'Reflection',
                'SPL',
                'SQLite',
                'SaxonC',
                'SimpleXML',
                'SplType',
                'Zend OPcache',
                'ZendCache',
                'ZendDebugger',
                'ZendUtils',
                'aerospike',
                'amqp',
                'apache',
                'apcu',
                'ast',
                'bcmath',
                'blackfire',
                'bz2',
                'calendar',
                'cassandra',
                'com_dotnet',
                'couchbase',
                'couchbase_v3',
                'crypto',
                'ctype',
                'cubrid',
                'curl',
                'date',
                'dba',
                'decimal',
                'dio',
                'dom',
                'ds',
                'enchant',
                'event',
                'exif',
                'fann',
                'ffmpeg',
                'fileinfo',
                'filter',
                'fpm',
                'ftp',
                'gd',
                'gearman',
                'geoip',
                'geos',
                'gettext',
                'gmagick',
                'gmp',
                'gnupg',
                'grpc',
                'hash',
                'http',
                'ibm_db2',
                'iconv',
                'igbinary',
                'imagick',
                'imap',
                'inotify',
                'interbase',
                'intl',
                'json',
                'judy',
                'ldap',
                'leveldb',
                'libevent',
                'libsodium',
                'libvirt-php',
                'libxml',
                'lua',
                'lzf',
                'mailparse',
                'mapscript',
                'mbstring',
                'mcrypt',
                'memcache',
                'memcached',
                'meminfo',
                'meta',
                'ming',
                'mongo',
                'mongodb',
                'mosquitto-php',
                'mqseries',
                'msgpack',
                'mssql',
                'mysql',
                'mysql_xdevapi',
                'mysqli',
                'ncurses',
                'newrelic',
                'oauth',
                'oci8',
                'odbc',
                'openssl',
                'parallel',
                'pcntl',
                'pcov',
                'pcre',
                'pdflib',
                'pdo_ibm',
                'pdo_mysql',
                'pdo_pgsql',
                'pdo_sqlite',
                'pgsql',
                'phpdbg',
                'posix',
                'pspell',
                'pthreads',
                'radius',
                'rar',
                'rdkafka',
                'readline',
                'recode',
                'redis',
                'regex',
                'rpminfo',
                'rrd',
                'session',
                'shmop',
                'snmp',
                'soap',
                'sockets',
                'sodium',
                'solr',
                'sqlite3',
                'sqlsrv',
                'ssh2',
                'standard',
                'stats',
                'stomp',
                'suhosin',
                'superglobals',
                'svm',
                'svn',
                'sybase',
                'sync',
                'sysvmsg',
                'sysvsem',
                'sysvshm',
                'tidy',
                'tokenizer',
                'uopz',
                'uuid',
                'uv',
                'v8js',
                'wddx',
                'win32service',
                'winbinder',
                'wincache',
                'wordpress',
                'xcache',
                'xdebug',
                'xhprof',
                'xlswriter',
                'xml',
                'xmlreader',
                'xmlrpc',
                'xmlwriter',
                'xsl',
                'xxtea',
                'yaf',
                'yaml',
                'yar',
                'zend',
                'zip',
                'zlib',
                'zmq',
                'zookeeper',
                'zstd'
            }
        },
    }
}
