zstyle :plugin:fast-syntax-highlighting theme "sonokai"
typeset -g FAST_THEME_NAME="sonokai"
: ${FAST_HIGHLIGHT_STYLES[sonokaidefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaiunknown-token]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaireserved-word]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaialias]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaisuffix-alias]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaibuiltin]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaifunction]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaicommand]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaiprecommand]:=fg=6}
: ${FAST_HIGHLIGHT_STYLES[sonokaicommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaihashed-command]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaipath]:=fg=6}
: ${FAST_HIGHLIGHT_STYLES[sonokaipath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[sonokaiglobbing]:=fg=6}
: ${FAST_HIGHLIGHT_STYLES[sonokaiglobbing-ext]:=fg=6,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaihistory-expansion]:=fg=6,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaisingle-hyphen-option]:=fg=3}
: ${FAST_HIGHLIGHT_STYLES[sonokaidouble-hyphen-option]:=fg=3}
: ${FAST_HIGHLIGHT_STYLES[sonokaiback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaisingle-quoted-argument]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[sonokaidouble-quoted-argument]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[sonokaidollar-quoted-argument]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[sonokaiback-or-dollar-double-quoted-argument]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaiback-dollar-quoted-argument]:=fg=6}
: ${FAST_HIGHLIGHT_STYLES[sonokaiassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokairedirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaicomment]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[sonokaivariable]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaimathvar]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaimathnum]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaimatherr]:=fg=1,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaiassign-array-bracket]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaifor-loop-variable]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaifor-loop-number]:=fg=9}
: ${FAST_HIGHLIGHT_STYLES[sonokaifor-loop-operator]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaifor-loop-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaiexec-descriptor]:=fg=9,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaihere-string-tri]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[sonokaihere-string-text]:=bg=11}
: ${FAST_HIGHLIGHT_STYLES[sonokaihere-string-var]:=fg=1,bg=11}
: ${FAST_HIGHLIGHT_STYLES[sonokaisecondary]:=none}
: ${FAST_HIGHLIGHT_STYLES[sonokaicase-input]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaicase-parentheses]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaicase-condition]:=bg=10}
: ${FAST_HIGHLIGHT_STYLES[sonokaicorrect-subtle]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaiincorrect-subtle]:=fg=1}
: ${FAST_HIGHLIGHT_STYLES[sonokaisubtle-separator]:=fg=8}
: ${FAST_HIGHLIGHT_STYLES[sonokaisubtle-bg]:=bg=10}
: ${FAST_HIGHLIGHT_STYLES[sonokaipath-to-dir]:=fg=6,underline}
: ${FAST_HIGHLIGHT_STYLES[sonokaipaired-bracket]:=bg=8}
: ${FAST_HIGHLIGHT_STYLES[sonokaibracket-level-1]:=fg=3,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaibracket-level-2]:=fg=6,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaibracket-level-3]:=fg=2,bold}
: ${FAST_HIGHLIGHT_STYLES[sonokaiglobal-alias]:=fg=4,bg=11}
: ${FAST_HIGHLIGHT_STYLES[sonokaisubcommand]:=fg=6}
: ${FAST_HIGHLIGHT_STYLES[sonokaisingle-sq-bracket]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaidouble-sq-bracket]:=fg=4}
: ${FAST_HIGHLIGHT_STYLES[sonokaidouble-paren]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokaioptarg-string]:=fg=2}
: ${FAST_HIGHLIGHT_STYLES[sonokaioptarg-number]:=fg=5}
: ${FAST_HIGHLIGHT_STYLES[sonokairecursive-base]:=none}
